### ISSUE TITLE
Fix It ASAP

### ISSUE THREAD

**Issue by RahulCvIsProSpem** [Team-Deadly/DEADLY-USERBOT#3]
![Screenshot_20220115-133251~2](https://user-images.githubusercontent.com/97778843/149614588-ec2f3e93-33c4-40f3-9058-fea481a8dd04.png)

**Comment by RahulCvIsProSpem** [comment]
Fix IT

**Comment by myselfloaders** [comment]
Yes

**Comment by piroXpower** [comment]
changed to Pyrogram now enjoy
